version: '3.9'

services:

  web:
    container_name: django-web
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - .env.dev
    ports:
      - "8000:8000"

  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - web

