#!/usr/bin/env bash

# 🚀 Script de Prueba Rápida - HIS+
# Uso: bash quick_test.sh

echo "╔════════════════════════════════════════╗"
echo "║  🏥 HIS+ - Inicialización Rápida      ║"
echo "╚════════════════════════════════════════╝"
echo ""

# Verificar si estamos en la carpeta correcta
if [ ! -f "docker-compose.yml" ]; then
    echo "❌ Error: Ejecuta este script desde la raíz del proyecto"
    echo "   Ubicación correcta: /home/sbuitrago/hisplus/"
    exit 1
fi

echo "📦 Construyendo e iniciando contenedores..."
docker compose down -v 2>/dev/null || true
docker compose up --build -d

echo ""
echo "⏳ Esperando a que inicie la base de datos..."
sleep 10

echo ""
echo "✅ Contenedores iniciados"
echo ""
echo "╔════════════════════════════════════════╗"
echo "║  📊 Sistema Listo para Usar            ║"
echo "╠════════════════════════════════════════╣"
echo "║                                        ║"
echo "║  🌐 Frontend: http://localhost:3000    ║"
echo "║  🔌 Backend:  http://localhost:8000    ║"
echo "║  🗄️  Base de datos: PostgreSQL (db)    ║"
echo "║                                        ║"
echo "╠════════════════════════════════════════╣"
echo "║  🔐 Credenciales de Prueba:            ║"
echo "╠════════════════════════════════════════╣"
echo "║                                        ║"
echo "║  Admin:                                ║"
echo "║    📧 admin@hospital.com               ║"
echo "║    🔑 admin123                         ║"
echo "║                                        ║"
echo "║  Médico:                               ║"
echo "║    📧 medico1@hospital.com             ║"
echo "║    🔑 medico1                          ║"
echo "║                                        ║"
echo "║  Enfermero:                            ║"
echo "║    📧 enfermero1@hospital.com          ║"
echo "║    🔑 enfermero1                       ║"
echo "║                                        ║"
echo "║  Personal ADM:                         ║"
echo "║    📧 admin1@hospital.com              ║"
echo "║    🔑 admin1                           ║"
echo "║                                        ║"
echo "╠════════════════════════════════════════╣"
echo "║  📈 Datos Cargados:                    ║"
echo "╠════════════════════════════════════════╣"
echo "║  ✓ 2 Sedes Hospitalarias               ║"
echo "║  ✓ 16 Departamentos                    ║"
echo "║  ✓ 7 Empleados (roles variados)        ║"
echo "║  ✓ 8 Pacientes                         ║"
echo "║  ✓ 8 Medicamentos                      ║"
echo "║  ✓ 5 Citas programadas                 ║"
echo "║  ✓ 3 Historias Clínicas                ║"
echo "║  ✓ 24 Equipos                          ║"
echo "║                                        ║"
echo "╠════════════════════════════════════════╣"
echo "║  🛠️  Comandos útiles:                  ║"
echo "╠════════════════════════════════════════╣"
echo "║                                        ║"
echo "║  Ver logs:                             ║"
echo "║  $ docker compose logs -f              ║"
echo "║                                        ║"
echo "║  Detener servicios:                    ║"
echo "║  $ docker compose down                 ║"
echo "║                                        ║"
echo "║  Reiniciar limpio:                     ║"
echo "║  $ docker compose down -v              ║"
echo "║  $ docker compose up --build -d        ║"
echo "║                                        ║"
echo "║  Acceder al backend:                   ║"
echo "║  $ docker compose exec backend bash    ║"
echo "║                                        ║"
echo "║  Ver base de datos:                    ║"
echo "║  $ docker compose exec db psql -U postgres -d his_central_db ║"
echo "║                                        ║"
echo "╚════════════════════════════════════════╝"
echo ""
echo "🎉 ¡Todo listo! Abre el navegador en http://localhost:3000"
