# Generated by Django 5.1.1 on 2025-11-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dept', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_med', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('stock', models.IntegerField()),
                ('unidad', models.CharField(max_length=50)),
                ('proveedor', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pac', models.CharField(max_length=150)),
                ('fecha_nac', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('dir_pac', models.CharField(max_length=200)),
                ('tel_pac', models.CharField(max_length=20)),
                ('tipo_doc', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PP', 'Pasaporte')], max_length=5)),
                ('num_doc', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='SedeHospitalaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sede', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Sedes_Hospitalarias',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_emp', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('tel_emp', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Médico'), ('ENFERMERO', 'Enfermero'), ('ADM', 'Personal Administrativo')], max_length=20)),
                ('hash_contra', models.CharField(max_length=255)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='his.departamento')),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('fecha_evento', models.DateTimeField()),
                ('ip_origen', models.GenericIPAddressField()),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to='his.empleado')),
            ],
            options={
                'db_table': 'Auditoria_Accesos',
            },
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_eq', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('FUERA_SERVICIO', 'Fuera de servicio')], max_length=30)),
                ('fecha_mantenimiento', models.DateField(blank=True, null=True)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='his.departamento')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to='his.empleado')),
            ],
            options={
                'db_table': 'Equipamiento',
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField()),
                ('diagnostico', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_registradas', to='his.empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='his.paciente')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_clinicas', to='his.sedehospitalaria')),
            ],
            options={
                'db_table': 'Historias_Clinicas',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='his.departamento')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='his.empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='his.paciente')),
            ],
            options={
                'db_table': 'Citas',
            },
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('fecha_emision', models.DateTimeField()),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='his.historiaclinica')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescripciones', to='his.medicamento')),
            ],
            options={
                'db_table': 'Prescripciones',
            },
        ),
        migrations.CreateModel(
            name='ReporteMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField()),
                ('tipo_reporte', models.CharField(max_length=100)),
                ('resumen', models.TextField()),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_medicos', to='his.sedehospitalaria')),
            ],
            options={
                'db_table': 'Reportes_Medicos',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='his.sedehospitalaria'),
        ),
    ]
